language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
matrix:
    allow_failures:
        - julia: nightly
after_success:
    - julia -e 'cd(Pkg.dir("SimJulia")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
    - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("SimJulia")); include(joinpath("docs", "make.jl"))'
